apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-ebs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-08b38231803d2c765
    fsType: ext4
